[formatter.rust]
command  = "cargo"
includes = ["*.rs"]
options  = ["--", "fmt"]

[formatter.deno]
command  = "deno"
excludes = [".beads/**", "lib/**", "node_modules/**", "static/js/**"]
includes = ["*.css", "*.html", "*.json", "*.md"]
options  = ["fmt"]

[formatter.rescript]
command  = "npx"
includes = ["*.res"]
options  = ["format", "rescript"]
