name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 from 19.03.2026
      - name: Install Nix
        uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
      - name: Setup cachix cache
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17 from 19.03.2026
        env:
          USER: runner
        with:
          name: hose
      - name: Check formatting
        run: nix develop -c treefmt --fail-on-change
      - name: Run clippy
        run: nix develop -c cargo clippy -- -D warnings
  test:
    name: Test
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 from 19.03.2026
      - name: Install Nix
        uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
      - name: Setup cachix cache
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17 from 19.03.2026
        env:
          USER: runner
        with:
          name: hose
      - name: Run tests
        run: nix develop -c cargo test
  build-dev-docker:
    name: Docker ${{ matrix.architecture }}
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker-image.yaml@build-docker-image-v1
    strategy:
      matrix:
        include:
          - architecture: x86_64-linux
            command: nix run -L .#docker-hose-dev-upload-x86_64-linux
    permissions:
      contents: read
      security-events: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: "commit"
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: "hose"
      build_file: "Cargo.toml"
      build_command: ${{ matrix.command }}
      docker_image_name: "hose-dev"
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-dev-docker-manifest:
    name: Docker manifest
    needs: build-dev-docker
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker-manifest.yaml@build-docker-manifest-v1
    permissions:
      contents: read
    with:
      version_type: "commit"
      docker_image_name: "hose-dev"
      docker_build_version: ${{ needs.build-dev-docker.outputs.docker_build_version }}
      docker_debug_version: ${{ needs.build-dev-docker.outputs.docker_debug_version }}
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
