name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: self-hosted-hoprnet-bigger
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 from 13.11.2025

      - name: Setup cachix cache
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15 from 20.05.2024
        with:
          name: hose

      - name: Install devenv
        run: nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Check formatting
        run: devenv shell -- treefmt --fail-on-change

      - name: Run clippy
        run: devenv shell -- cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: self-hosted-hoprnet-bigger
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 from 13.11.2025

      - name: Setup cachix cache
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15 from 20.05.2024
        with:
          name: hose

      - name: Install devenv
        run: nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Run tests
        run: devenv shell -- cargo test

  build-dev-image:
    name: Build dev image
    runs-on: self-hosted-hoprnet-bigger
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 from 13.11.2025

      - name: Setup cachix cache
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15 from 20.05.2024
        with:
          name: hose

      - name: Install devenv
        run: nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Build dev container
        run: devenv container build hose-dev
