name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - "charts/**"
jobs:
  build-docker:
    name: Docker ${{ matrix.architecture }}
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker-image.yaml@tb/202604-update-version
    strategy:
      matrix:
        include:
          - architecture: x86_64-linux
            command: nix run -L .#docker-hose-upload-x86_64-linux
    permissions:
      contents: read
      security-events: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: ${{ startsWith(github.ref, 'refs/tags/v') && 'release' || 'commit' }}
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: "hose"
      build_file: "Cargo.toml"
      build_command: ${{ matrix.command }}
      docker_image_name: "hose"
      runner: depot-ubuntu-24.04
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-docker-manifest:
    name: Docker manifest
    needs: build-docker
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker-manifest.yaml@tb/202604-update-version
    permissions:
      contents: read
    with:
      version_type: ${{ startsWith(github.ref, 'refs/tags/v') && 'release' || 'commit' }}
      docker_image_name: "hose"
      docker_build_version: ${{ needs.build-docker.outputs.docker_build_version }}
      docker_debug_version: ${{ needs.build-docker.outputs.docker_debug_version }}
      runner: depot-ubuntu-24.04
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
  tag-latest:
    name: Tag latest
    if: github.ref == 'refs/heads/main'
    needs: [build-docker, build-docker-manifest]
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    env:
      REGISTRY: europe-west3-docker.pkg.dev/hoprassociation/docker-images
    steps:
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@setup-gcp-v2
        with:
          google_credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          login_artifact_registry: 'true'
          install_sdk: 'false'
      - name: Tag as latest
        run: |
          docker buildx imagetools create \
            --tag "$REGISTRY/hose:latest" \
            "$REGISTRY/hose:${{ needs.build-docker.outputs.docker_build_version }}"
