name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"

jobs:
  build-release-image:
    name: Build and push release image
    runs-on: self-hosted-hoprnet-bigger
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 from 13.11.2025

      - name: Setup cachix cache
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15 from 20.05.2024
        with:
          name: hose

      - name: Install devenv
        run: nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build release container
        run: devenv container build hose

      - name: Push release container
        run: devenv container --registry docker://ghcr.io/ copy hose
