name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"

jobs:
  build-release-image:
    name: Build and push release image
    runs-on: self-hosted-hoprnet-bigger
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 from 19.03.2026

      - name: Setup cachix cache
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17 from 19.03.2026
        env:
          USER: runner
        with:
          name: hose

      - name: Install devenv
        run: command -v devenv || nix profile install --accept-flake-config github:cachix/devenv/latest

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build release container
        run: devenv container build hose

      - name: Push release container
        run: devenv container --registry docker://ghcr.io/ copy hose
